services:
  app.my_logger_service:
    class: MyLoggerService

  app.my_service:
    class: MyService
    kwargs:
      logger: '@app.my_logger_service'
      port: '%http.port:Int32%'

  echo_array_service:
    class: EchoArrayService
    kwargs:
      arr: '%context(str_list):Array(String)%'
